FROM tiangolo/uvicorn-gunicorn-fastapi:latest

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN groupadd -r bookish && useradd -r -g bookish bookish

COPY ./app /app/app
COPY ./alembic /app/alembic
COPY alembic.ini /app/